[package]
name = "html"
version = "0.1.0"
edition = "2024"

[dependencies]
html5ever = "0.31.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
strum = "0.27.1"
strum_macros = "0.27.1"
